export const MOVE_SNAKE = "MOVE_SNAKE"
export const CHANGE_DIRECTION = "CHANGE_DIRECTION"
export const ADD_USER = "ADD_USER"
export const USERS_LIST = "USERS_LIST"
export const USERS_ID = "USERS_ID"

export const UPDATE_POINT = 'UPDATE_POINT'
export const SET_ACTIVE = 'SET_ACTIVE'


export const WS_CHANGE_DIRECTION = "WS_CHANGE_DIRECTION"
export const WS_SET_ACTIVE = "WS_SET_ACTIVE"

export const PLAYER_READY = 'PLAYER_READY'
export const OPPONENT_READY = 'OPPONENT_READY'
export const OPP_CHANGE_DIRECTION = 'OPP_CHANGE_DIRECTION'